task:
    name: source t
    container:
        image: ubuntu:20.04
        #cpu: 16
        #memory: 24G
    t_script: source t

check_task:
  name: ccache check
  container:
    image: node:latest
    cpu: 1
    memory: 200M
  node_modules_cache:
    folder: sb/node_modules
    fingerprint_script: cat sb/commands.txt 
    populate_script: npm install --prefix sb
  test_script: npm start --prefix sb
