task:
    # Basic metadata:
    name: t2
    # The build machine:
    container:
        image: ubuntu:20.04
          #cpu: 16
          #memory: 24G
          #        cpu: 16
          #memory: 24G

    # No environment variables provided.

    # Instructions:
    run_script: source r
