env:                            #env to pass to all tasks
  CIRRUS_CLONE_DEPTH: 1         #clone with depth=1 in all tasks

source_task:
    name: source t              #source t shows in task/checklist in github
    container:                  #docker container
        matrix:                   #run source t in both ubuntu 20 and 18
          - image: ubuntu:20.04   #image:tag
          - image: ubuntu:18.04
        cpu: 0.2                #min=0.2,max=16
        memory: 200M            #min=your need, max=24G
    silent_background_script: sleep 2   #bg script by cirrus, stops when all tasks ends
    bground_script: sleep 2 &   #bg by us, runs until finishes
    fground_script: sleep 2     #fg by us, runs until finishes
    t_script: source t          #t=Run t inside source t
    printenv_script: printenv

check_task:
  name: ccache check
  container:
    image: node:latest
    cpu: 0.2
    memory: 500M
  node_modules_cache:                           #node_modules=Populate node_modules cache 
    folder: sb/node_modules                     #sb/node_modules folder will be saved as cache, so no need to regenarate
    fingerprint_script: cat sb/commands.txt     #change in this output will trigger regenerate cache
    populate_script: npm install --prefix sb    #how to generate cache
  test_script: npm start --prefix sb            #test=Run test inside ccache check
  printenv_script: printenv
